################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
ASM_UPPER_DEPS := 
SX_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/board/ra6m5_ck \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_ether \
ra/fsp/src/r_ether_phy \
ra/fsp/src/r_ether_phy/targets/DP83620 \
ra/fsp/src/r_ether_phy/targets/ICS1894 \
ra/fsp/src/r_ether_phy/targets/KSZ8041 \
ra/fsp/src/r_ether_phy/targets/KSZ8091RNB \
ra/fsp/src/r_flash_hp \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/adaptors \
ra/fsp/src/r_sce/crypto_procedures/src/sce9/plainkey/primitive \
ra/fsp/src/r_sci_uart \
ra/fsp/src/rm_comms_i2c \
ra/fsp/src/rm_hs300x \
ra/fsp/src/rm_netx_secure_crypto \
ra/fsp/src/rm_netxduo_ether \
ra/fsp/src/rm_threadx_port \
ra/fsp/src/rm_zmod4xxx/iaq_1st_gen \
ra/fsp/src/rm_zmod4xxx/oaq_1st_gen \
ra/fsp/src/rm_zmod4xxx \
ra/microsoft/azure-rtos/netxduo/addons/auto_ip \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src/azure/core \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src/azure/iot \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src/azure/platform \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/deps/flatcc/src/runtime \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src/collectors \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src/model \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src/serializer/extensions \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src/serializer \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src/utils/collection \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/iot-security-module-core/src/utils \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/src/collectors \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/src/model/objects \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot/azure_iot_security_module/src/utils \
ra/microsoft/azure-rtos/netxduo/addons/azure_iot \
ra/microsoft/azure-rtos/netxduo/addons/cloud \
ra/microsoft/azure-rtos/netxduo/addons/dhcp \
ra/microsoft/azure-rtos/netxduo/addons/dns \
ra/microsoft/azure-rtos/netxduo/addons/ftp \
ra/microsoft/azure-rtos/netxduo/addons/http \
ra/microsoft/azure-rtos/netxduo/addons/mqtt \
ra/microsoft/azure-rtos/netxduo/addons/nat \
ra/microsoft/azure-rtos/netxduo/addons/pop3 \
ra/microsoft/azure-rtos/netxduo/addons/smtp \
ra/microsoft/azure-rtos/netxduo/addons/snmp \
ra/microsoft/azure-rtos/netxduo/addons/sntp \
ra/microsoft/azure-rtos/netxduo/addons/telnet \
ra/microsoft/azure-rtos/netxduo/addons/tftp \
ra/microsoft/azure-rtos/netxduo/addons/web \
ra/microsoft/azure-rtos/netxduo/common/src \
ra/microsoft/azure-rtos/netxduo/crypto_libraries/src \
ra/microsoft/azure-rtos/netxduo/nx_secure/src \
ra/microsoft/azure-rtos/threadx/common/src \
ra_gen \
src \
src/I2C \
src/SEGGER_RTT \
src/console_menu \
src/flash \
src/ob1203_bio/KALMAN \
src/ob1203_bio/OB1203 \
src/ob1203_bio/SAVGOL \
src/ob1203_bio/SPO2 \

